### ISSUE TITLE
Good results. How to test a+b and style mixing？

### ISSUE THREAD

**Issue by c1a1o1** [EzioBy/padinv#2]
Good results. How to test a+b and style mixing

**Comment by EzioBy** [comment]
Thanks for your attention. 
You can test 'style mixing' with the codes of [pSp](https://github.com/eladrich/pixel2style2pixel). Specifically, after inverting the two inputs with the pSp encoder you can get two groups of 18x512 latent codes (for 1024x1024 images). We then combine the former 7x512 latent codes corresponding to one input image and the latter 11x512 latent codes corresponding to the other image to get a new group of latent codes. The style mixing result could be obtained by sending these combined (mixed) 18x512 latent codes to the pre-trained generator.
Similarly, for our 'a+b' results we mix the paddings and  style latent codes of the two inputs, as described in subsec 4.3. We will provide a script recently for your convenience.

**Comment by c1a1o1** [comment]
Thanks  very much!
