### ISSUE TITLE
padding map visualization

### ISSUE THREAD

**Issue by TaekyungKi** [EzioBy/padinv#5]
Hi thank you for your interesting work !
Have you visualized the padding map? I wonder how the padding map is generated, since it is learned unsupervisedly and used as kind of "shell" w.r.t. generator feature map.

Best,

**Comment by EzioBy** [comment]
Hi, sorry for the late reply. I'm busy with my graduation project recently.

As you have stated, the padding map is extracted by the encoder while the encoder targeting to faithfully reconstruct the input image is trained without any specific constraint to the padding coefficients.

If you are interested in visualizing the paddings, I think you can store the paddings during testing and use _seaborn.heatmap_ to visualize them. And you can add these codes here: https://github.com/EzioBy/padinv/blob/49304d68435cbb9e7e744c0892c9e1c80bf395a4/metrics/gan_inversion_metric.py#L140
